// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9x6EQ4uZIDUAsGCod-DdWbKzpiD1-eNo',
    appId: '1:52367554747:web:4371d85eabe98c9409119e',
    messagingSenderId: '52367554747',
    projectId: 'news-reader-app-dd490',
    authDomain: 'news-reader-app-dd490.firebaseapp.com',
    storageBucket: 'news-reader-app-dd490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EVXP2k99NMiIpXkKyiKZ4j-WXoI_FHU',
    appId: '1:52367554747:android:72a6ce4ac911159809119e',
    messagingSenderId: '52367554747',
    projectId: 'news-reader-app-dd490',
    storageBucket: 'news-reader-app-dd490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcOG8e4e17Wc76q072uLi5LfWNRdtQ6OE',
    appId: '1:52367554747:ios:a00a94e8fe6546e409119e',
    messagingSenderId: '52367554747',
    projectId: 'news-reader-app-dd490',
    storageBucket: 'news-reader-app-dd490.appspot.com',
    iosBundleId: 'com.example.newsReaderApp',
  );
}
